### ISSUE TITLE
Criar rota com o status do pedido na transportadora escolhida

### ISSUE THREAD

**Issue by TRios04** [Programacao-para-web-2023-01/ceublivre-api-null#3]
Nessa rota, o usuário insere o ID do pacote e recebe o status atual (a enviar, em trânsito, entregue) com a localização do pedido de acordo com os dados da transportadora.

**Comment by vctg1** [comment]
Entrada - código do pedido
Saída - Localização aproximada, data e horário em que foi registrado, status atual (a enviar, em trânsito, entregue)
